defaults:
  - nlp/default
_target_: lightning_transformers.task.nlp.text_classification.TextClassificationDataModule
cfg:
  dataset_name: /workspace/CALM/lightning-transformers/lightning_transformers/task/nlp/klue_sts
  max_length: 128
  truncation: longest_first
